<?php
/**
 * Created by PhpStorm.
 * User: matpif
 * Date: 13/04/16
 * Time: 19:36
 */
/**
 * @var $_login LoginController
 */
$_login = $this;
?>
<div class="login-card">
    <img class="profile-img-card" src="<?php echo $_login->getUrlImage('/avatar.png') ?>">
    <p class="center"><b>Bienvenue</b><br/>Entrer votre adresse mail</p>
    <form class="form-signin" action="<?php echo $_login->getUrlAction('forgetPassword') ?>" method="post" name="forgetPassword">
        <span class="reauth-email"></span>
        <input type="email" name="email" class="form-control" id="email" autofocus required placeholder="Email">
        <button type="submit" class="btn btn-default">Nouveau mot de passe</button>
    </form>
</div>
