<?php
/**
 * Created by PhpStorm.
 * User: matpif
 * Date: 25/04/16
 * Time: 11:49
 */
/** @var Controller $this */
/** @var Access $_access */
$_access = Access::getInstance();
/** @var MatchsController $_matchs */
$_matchs = Controller::getController('MatchsController');
/** @var ClassementController $_classement */
$_classement = Controller::getController('ClassementController');
/** @var MonProfilController $_monProfil */
$_monProfil = Controller::getController('MonProfilController');
/** @var AdminController $_admin */
$_admin = Controller::getController('AdminController');
/** @var LoginController $_login */
$_login = Controller::getController('LoginController');
/** @var ShareController $_share */
$_share = Controller::getController('ShareController');
/** @var MonClassementController $_share */
$_monclassement = Controller::getController('MonClassementController');
/** @var AboutController $_about */
$_about = Controller::getController('AboutController');
?>
<header>
    <nav class="navbar navbar-default" style="z-index: 1;">
        <div class="container-fluid width">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#menu_header" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">Paris</a>
            </div>
            <div class="collapse navbar-collapse" id="menu_header">
                <ul class="nav navbar-nav">
                    <li class="<?php echo ($_access->isActivePage($_matchs->getPage()))?'active':''; ?>"><a href="<?php echo $_matchs->getUrl(); ?>">Matchs / Paris</a></li>
                    <li class="<?php echo ($_access->isActivePage($_monclassement->getPage()))?'active':''; ?>"><a href="<?php echo $_monclassement->getUrl(); ?>">Mon Classement par poule</a></li>
                    <li class="<?php echo ($_access->isActivePage($_share->getPage()))?'active':''; ?>"><a href="<?php echo $_share->getUrl(); ?>">Paris partagés</a></li>
                    <li class="<?php echo ($_access->isActivePage($_classement->getPage()))?'active':''; ?>"><a href="<?php echo $_classement->getUrl(); ?>">Classement</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <?php if ($_access->getCurrentUser()): ?>
                        <li>
                            <a href="<?php echo $_monProfil->getUrl(); ?>">
                                <span class="glyphicon glyphicon-user"></span>
                                <?php echo $_access->getCurrentUser()->getAttribute('login'); ?>
                            </a>
                        </li>
                    <?php endif; ?>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="glyphicon glyphicon-home" aria-hidden="true"></span> <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="<?php echo $_monProfil->getUrl(); ?>"><span class="glyphicon glyphicon-user"></span>&nbsp;Profil</a></li>
                            <?php if ($_access->getCurrentUser() && $_access->getCurrentUser()->getAttribute('privilege') == UtilisateurModel::PRIVILEGE_ADMIN): ?>
                                <li><a href="<?php echo $_admin->getUrl(); ?>"><span class="glyphicon glyphicon-dashboard"></span>&nbsp;Administration</a></li>
                            <?php endif; ?>
                            <li><a href="<?php echo $_login->getUrlAction('disconnect'); ?>"><span class="glyphicon glyphicon-log-out"></span>&nbsp;Se déconnecter</a></li>
                            <li><a href="<?php echo $_about->getUrl(); ?>"><span class="glyphicon glyphicon-question-sign"></span>&nbsp;About</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
