<?php
/**
 * Created by PhpStorm.
 * User: matpif
 * Date: 25/04/16
 * Time: 11:49
 */
/** @var Controller $this */
/** @var Access $_access */
$_access = Access::getInstance();
?>
<header>
    <nav class="navbar navbar-default">
        <div class="container-fluid width">
            <div class="navbar-header">
                <a class="navbar-brand" href="/">Paris</a>
            </div>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li class="<?php echo ($_access->isActivePage('matchs'))?'active':''; ?>"><a href="/matchs">Matchs</a></li>
                    <li class="<?php echo ($_access->isActivePage('myParis'))?'active':''; ?>"><a href="/myParis">Mes Paris</a></li>
                    <li class="<?php echo ($_access->isActivePage('classement'))?'active':''; ?>"><a href="/classement">Classement</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="glyphicon glyphicon-user" aria-hidden="true"></span> <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="/profile">Profile</a></li>
                            <li><a href="/login/disconnect">Se déconnecter</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
