<?php
/**
 * Created by PhpStorm.
 * User: matpif
 * Date: 13/04/16
 * Time: 19:36
 */
/**
 * @var $_login LoginController
 */
$_login = $this;
?>
<div class="login-card">
    <img class="profile-img-card" src="/images/avatar.png">
    <p class="center">Bienvenue<br/>Merci de vous identifier pour continuer</p>
    <form class="form-signin" action="<?php echo $_login->getUrlAction('signIn') ?>" method="post">
        <span class="reauth-email"></span>
        <input type="email" name="email" class="form-control" id="email" autofocus required placeholder="Email">
        <input type="password" name="password" class="form-control" id="password" required placeholder="Mot de passe">

        <button type="submit" class="btn btn-default">Se connecter</button>
    </form>
</div>
