<?php
/**
 * User: corpas
 * Date: 08/05/16
 * Time: 21:08
 */
/** @var MatchsController $_match */
$_match = $this;
$_utilisateur = Access::getInstance()->getCurrentUser();
$_matchsCollection = $_match->getAllMatch();
$_pariCollection = new PariCollection();
$_equipeCollection = new EquipeCollection();
/** Début tableau matchs **/
?>
<div>
	<form action="">
		<?php
		/** @var MatchModel $match */
		foreach ($_matchsCollection as $match):
			/* Récuperer le score du match réel si déjà joué, sinon "-" */
			$equipe_1 = $_equipeCollection->loadById($match->getAttribute('equipe_id_1'));
			$equipe_2 = $_equipeCollection->loadById($match->getAttribute('equipe_id_2'));
			$pari = $_match->getPari($match);
			?>
			<div class="test" align="center">
				<div class="row center"><?php echo $match->getAttribute("date"); ?></div>
			    <div class="row cont">
			        <div class="col-lg-5" align="left">
			            <img src="<?php echo $_match->getUrlImage('/pays/' . $equipe_1->getAttribute('image')) ?>"><?php echo $equipe_1->getAttribute('name') ?>
			        </div>
			        <div class="col-lg-2 score">
			            <input class="form-control" type="number" name="score_equipe_1" value="<?php echo ($pari)?$pari->getAttribute("score_equipe_1"):'' ?>"> - <input class="form-control" type="number" name="score_equipe_2" value="<?php echo ($pari)?$pari->getAttribute("score_equipe_2"):'' ?>">
			        </div>
			        <div class="col-lg-5" align="right"><?php echo $equipe_2->getAttribute('name') ?><img src="<?php echo $_match->getUrlImage('/pays/' . $equipe_2->getAttribute('image'))?>">
			        </div>
			    </div>
			    <div class="row">
			        <div class="col-lg-offset-5 col-lg-2">
			            <?php echo $match->getScore(1)." - ".$match->getScore(2) ?>
			        </div>
			    </div>
			</div>
		<?php endforeach; ?>
	</form>
</div>
