<?php
/**
 * User: corpas
 * Date: 08/05/16
 * Time: 21:08
 */
/** @var MatchsController $_match */
$_match = $this;
$_utilisateur = Access::getInstance()->getCurrentUser();

/** Début tableau matchs **/
?>
<div>
	<table class="table table-striped">
		<tr>
			<th>Date</th>
			<th>Image 1</th>
			<th>Equipe 1</th>
			<th>Score</th>
			<th>Equipe 2</th>
			<th>Image 2</th>
		</tr>
<?php

$collection_matchs = new MatchCollection();
$collection_matchs->loadAll(["date" => Collection::SORT_ASC]);

$collection_paris = new PariCollection();

/** @var MatchModel $match */
foreach ($collection_matchs as $match):
	/* Récuperer le score du match réel si déjà joué, sinon "-" */
	$equipe_1 = (new EquipeCollection())->loadById($match->getAttribute('equipe_id_1'));
    $equipe_2 = (new EquipeCollection())->loadById($match->getAttribute('equipe_id_2'));

    $pari = $collection_paris->load(array("utilisateur_id" => $_utilisateur->getAttribute('utilisateur_id'), "match_id" => $match->getAttribute('id')))->getFirstRow();
?>
		<tr>
			<td><?php echo $match->getAttribute("date") ?></td>
			<td><?php echo '<img width="35px" src="/images/pays/' . $equipe_1->getAttribute('image') . '" />' ?></td>
			<td><?php echo $equipe_1->getAttribute('name') ?></td>
			<td>
				<?php echo ($pari)?$pari->getAttribute("score_equipe_1")." - ".$pari->getAttribute("score_equipe_1"):'' ?>
				<span class="small_grey"><?php echo $match->getAttribute('score_equipe_1')." - ".$match->getAttribute('score_equipe_2') ?></span>
			</td>
			<td><?php echo $equipe_2->getAttribute('name') ?></td>
			<td><?php echo '<img width="35px" src="/images/pays/' . $equipe_2->getAttribute('image') . '" />' ?></td>
		</tr>
<?php endforeach; ?>
	</table>
</div>