<?php
/**
 * User: corpas
 * Date: 08/05/16
 * Time: 21:08
 */
/** @var MatchsController $_match */
$_match = $this;
$_utilisateur = Access::getInstance()->getCurrentUser();
$_matchsCollection = $_match->getAllMatch();
$_equipeCollection = new EquipeCollection();
/** Début tableau matchs **/
?>
<div>
	<form action="<?php echo $_match->getUrlAction('save'); ?>" method="POST">
		<div class="row">
        	<button class="btn btn-info mrg col-lg-1" type="submit">SAVE</button>
		</div>
		<?php
		$array_id = array();
		/** @var MatchModel $match */
		foreach ($_matchsCollection as $match):
			/* Récuperer le score du match réel si déjà joué, sinon "-" */
			$equipe_1 = $_equipeCollection->loadById($match->getAttribute('equipe_id_1'));
			$equipe_2 = $_equipeCollection->loadById($match->getAttribute('equipe_id_2'));
			
            $pari = $_match->getPari($match);
			?>
			<div class="row row_match center">
				<div class="row center date"><?php echo date_format(new DateTime($match->getAttribute("date")), 'd/m/Y H:i'); ?></div>
			    <div class="row cont">
			        <div class="col-lg-5" align="left">
			            <img src="<?php echo $_match->getUrlImage('/pays/' . $equipe_1->getAttribute('image')) ?>" class="flag">
						<p class="match"><?php echo $equipe_1->getAttribute('name') ?></p>
			        </div>
			        <div class="col-lg-2 score">
			            <input class="form-control match" type="number" name="paris[<?php echo $match->getAttribute('id') ?>][score_equipe_1]" value="<?php echo ($pari)?$pari->getAttribute("score_equipe_1"):'' ?>"> - <input class="form-control match" type="number" name="paris[<?php echo $match->getAttribute('id') ?>][score_equipe_2]" value="<?php echo ($pari)?$pari->getAttribute("score_equipe_2"):'' ?>">
			        </div>
			        <div class="col-lg-5" align="right">
						<p class="match"><?php echo $equipe_2->getAttribute('name') ?></p>
						<img src="<?php echo $_match->getUrlImage('/pays/' . $equipe_2->getAttribute('image'))?>" class="flag">
			        </div>
			    </div>
			    <div class="row">
			        <div class="col-lg-offset-5 col-lg-2">
						<?php if ($match->getScore(1) && $match->getScore(2)): ?>
			            	<?php echo $match->getScore(1)." - ".$match->getScore(2) ?>
						<?php endif; ?>
			        </div>
			    </div>
			</div>
		<?php endforeach; ?>
		<div class="row">
			<button class="btn btn-info mrg col-lg-1" type="submit">SAVE</button>
		</div>
	</form>
</div>
