<?php
/**
 * Created by PhpStorm.
 * User: matpif
 * Date: 19/06/16
 * Time: 16:54
 */
/** @var ClassementController $_userPoint */
$_userPoint = $this;
$_userSelected = $_userPoint->getUserSelected();

if ($_userSelected): ?>
    <?php $_paris = (new PariCollection())->loadByQuery("SELECT pari.*
                                        FROM pari
                                        INNER JOIN match
                                            ON match.id = pari.match_id
                                            AND match.date < datetime('now')
                                        WHERE pari.utilisateur_id = :utilisateur_id", ['utilisateur_id' => $_userSelected->getAttribute('id')]); ?>
    <table class="table table-striped">
        <tr>
            <th>Match</th>
            <th>Points</th>
        </tr>
        <?php /** @var $pari PariModel */ ?>
        <?php foreach ($_paris as $pari) : ?>
            <?php
            $match = $_userPoint->getMatch($pari->getAttribute('match_id'));
            ?>
            <tr>
                <td><?php echo $match->getEquipe_1()->getAttribute('name').' vs '.$match->getEquipe_2()->getAttribute('name') ?></td>
                <td><?php echo $pari->getScore(); ?></td>
            </tr>
        <?php endforeach; ?>
    </table>
<?php endif; ?>
