---
- name: Installation de l'application
  hosts: paris
  remote_user: root
  vars:
    - domain: exemple.com
    - port: 80
    - web_root: /var/www
    - git_repo: https://github.com/Matpif/Paris.git
    - git_root: /root/Paris
    - git_branch: master

  roles:
    - server

  tasks:
    - name: "Config {{domain}}"
      template: src=templates/nginx.j2 dest=/etc/nginx/sites-available/{{ domain }} force=yes
      become: true
    - name: Appliquation de la config
      become: true
      file: src=/etc/nginx/sites-available/{{ domain }} dest=/etc/nginx/sites-enabled/{{ domain }} state=link
    - name: Reload Nginx
      service: name=nginx state=reloaded
      become: true
    - name: Reload PHP-FPM
      service: name=php7.0-fpm state=reloaded
      become: true
    - name: Mise à jour du dépôt
      git: repo={{git_repo}}
                 dest={{git_root}}
                 version={{git_branch}}
                 force=yes
                 accept_hostkey=yes
    - name: Deploy to web root
      command: rsync -ac {{git_root}}/ {{web_root}}/{{domain}} --delete-after --chown=www-data:www-data
      become: true
...