<html>
<body>
Bienvenue sur l'application Paris
<br/><br/>

Voici les identifiants pour vous connectez:<br/>
Mail: <?php echo $params['mail']; ?><br/>
Mot de passe: <?php echo $params['password']; ?><br/><br/>

Vous pourrez changer votre mot de passe dans votre profil utilisateur une fois connecté.<br/>
<?php 'https://'.ReadIni::getInstance()->getAttribute('general', 'root_url'); ?>
</body>
</html>