<?php
/**
 * Created by PhpStorm.
 * User: matpif
 * Date: 04/05/16
 * Time: 16:57
 */
/** @var AdminController $_admin */
$_admin = $this;
?>
<div class="row">
    <div class="col-lg-4 col-lg-offset-4 col-md-8 col-md-offset-2">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Nouveau Match</h3>
            </div>
            <div class="panel-body">
                <form action="<?php echo $_admin->getUrlAction('addMatch'); ?>" method="POST">

                    <button type="submit" class="btn btn-default">Enregistrer</button>
                </form>
            </div>
        </div>
    </div>
</div>
