<?php
/**
 * Created by PhpStorm.
 * User: matpif
 * Date: 04/05/16
 * Time: 16:57
 */
/** @var AdminController $_admin */
$_admin = $this;
$_newUser = $_admin->getNewUser();
?>
<div class="row">
    <div class="col-lg-4 col-lg-offset-4 col-md-8 col-md-offset-2">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Utilisateur</h3>
            </div>
            <div class="panel-body">
                <form action="<?php echo $_admin->getUrlAction('addUser'); ?>" method="POST">
                    <?php if ($_newUser->getAttribute('id')): ?>
                        <input type="hidden" name="id" value="<?php echo $_newUser->getAttribute('id'); ?>"/>
                    <?php endif; ?>
                    <div class="form-group">
                        <label for="login">Login *</label>
                        <input type="text" class="form-control" id="login" placeholder="Login" name="login" value="<?php echo $_newUser->getAttribute('login') ?>" required>
                    </div>

                    <div class="form-group">
                        <label for="lastName">Nom</label>
                        <input type="text" class="form-control" id="lastName" placeholder="Nom" name="lastName" value="<?php echo $_newUser->getAttribute('lastName') ?>">
                    </div>

                    <div class="form-group">
                        <label for="firstName">Prénom</label>
                        <input type="text" class="form-control" id="firstName" placeholder="Prénom" name="firstName" value="<?php echo $_newUser->getAttribute('firstName') ?>">
                    </div>

                    <div class="form-group">
                        <label for="email">Email *</label>
                        <input type="email" class="form-control" id="email" placeholder="Email" name="email" value="<?php echo $_newUser->getAttribute('email') ?>" required>
                    </div>

                    <div class="form-group">
                        <label for="privilege">Privilège *</label>
                        <select name="privilege" id="privilege">
                            <option value="<?php echo UtilisateurModel::PRIVILEGE_USER; ?>" <?php echo ($_newUser->getAttribute('privilege') == UtilisateurModel::PRIVILEGE_USER)?'selected':''; ?> >Utilisateur</option>
                            <option value="<?php echo UtilisateurModel::PRIVILEGE_ADMIN; ?> <?php echo ($_newUser->getAttribute('privilege') == UtilisateurModel::PRIVILEGE_ADMIN)?'selected':''; ?>">Administrateur</option>
                        </select>
                    </div>

                    <button type="submit" class="btn btn-default">Enregistrer</button>
                </form>
            </div>
        </div>
    </div>
</div>
