<?php
/**
 * Created by PhpStorm.
 * User: matpif
 * Date: 04/05/16
 * Time: 21:07
 */
/** @var AdminController $_admin */
$_admin = $this;
/** @var LoginController $_login */
$_login = Controller::getController('LoginController');
?>
<header>
    <nav class="navbar navbar-inverse" style="z-index: 1;">
        <div class="container-fluid width">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#menu_header" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="<?php echo $_admin->getUrl(); ?>">Administration Paris</a>
            </div>
            <div class="collapse navbar-collapse" id="menu_header">
                <ul class="nav navbar-nav">
                    <li class=""><a href="<?php echo $_admin->getUrlAction('listUser'); ?>">Utilisateurs</a></li>
                    <li class=""><a href="<?php echo $_admin->getUrlAction('listMatch'); ?>">Matchs</a></li>
                    <li class=""><a href="<?php echo $_admin->getUrlAction('newPoule'); ?>">Ajouter Poule</a></li>
                    <li class=""><a href="<?php echo $_admin->getUrlAction('newEquipe'); ?>">Ajouter Equipe</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <?php // echo $_access->getCurrentUser()->getAttribute('login'); ?>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="glyphicon glyphicon-user" aria-hidden="true"></span> <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="/"><span class="glyphicon glyphicon-chevron-left"></span>Retour</a></li>
                            <li><a href="<?php echo $_login->getUrlAction('disconnect'); ?>"><span class="glyphicon glyphicon-log-out"></span>&nbsp;Se déconnecter</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
